import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
import '@angular/material/prebuilt-themes/purple-green.css';
import './style.css'
// RxJS
import 'rxjs';
